import { useQuery } from '@apollo/client';
import { gql } from 'apollo-server-micro';

import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useForm } from 'react-hook-form';
import { IUserModel } from '../models/User';

type FormData = {
  name: string;
  email: string;
};

const Home: NextPage = () => {
  const getAllUsersQuery = gql`
    query {
      getAllUsers {
        _id
        name
        email
      }
    }
  `;
  const { data, error, loading } = useQuery(getAllUsersQuery);

  const {
    register,
    setValue,
    handleSubmit,
    formState: { errors },
  } = useForm<FormData>();

  const onSubmit = handleSubmit((data) => {});

  return (
    <div className="grid grid-cols-1 place-items-center min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl font-black text-center text-blue-700">
          Let&apos;s create an amazing Fullstack NextJS Graphql app
        </h1>

        <form
          onSubmit={onSubmit}
          className="flex gap-4 items-center justify-center mt-20"
        >
          <label>Name</label>
          <input
            className="ring-1 rounded-md p-2"
            {...register('name')}
            type="text"
          />
          <label>Email</label>
          <input
            className="ring-1 rounded-md p-2"
            {...register('email')}
            type="email"
          />
          <button type="submit">Submit data GRAPHQL</button>
        </form>

        <button>Get All Users from the Server</button>

        {data && (
          <div className="mt-20">
            <h2 className="text-2xl font-black text-center text-blue-700">
              All Users
            </h2>
            <ul>
              {data.getAllUsers.map((user: IUserModel) => (
                <li key={user._id}>
                  <div>
                    <span>{user.name}</span>
                    <span>{user.email}</span>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
